export const slideTitles = [
  "Frozen Echo",
  "Silver Dusk",
  "Neon Horizon",
  "Glass Reverie",
  "Broken Compass",
  "Ashen Veil",
  "Velvet Static",
  "Phantom Gaze",
  "Whispering Ember",
  "Eternal Fracture",
  "Frozen Echo",
  "Silver Dusk",
  "Neon Horizon",
  "Glass Reverie",
  "Broken Compass",
  "Ashen Veil",
  "Velvet Static",
  "Phantom Gaze",
  "Whispering Ember",
  "Eternal Fracture",
];
